In [ ]:
import time
from Five_Robot_Control import *
import cv2
import numpy as np
from calibration import *
from Five_Robot_kinematics import *

robot_control = Five_Robot_Control()
calibration=Cam_Calibration()
five_robot_kinematics=Five_Robot_kinematics()
def robot_pick(pixel_x, pixel_y):
        point_x, point_y = calibration.calibration(pixel_x, pixel_y)  # 像素坐标得到世界坐标
        arr1, arr2, arr3, arr4 = five_robot_kinematics.arr(point_x, point_y, 0)  # 最后一个为Z轴，输出四个角度
        robot_control.bus_servo_niuju_on(0xfe)
        time.sleep(0.5)
        robot_control.bus_servo_all(30, 58, 170, 217, 0, 1000)
        time.sleep(2)
        robot_control.bus_servo_all(arr1, arr2, arr3, arr4, 0, 1000)
        time.sleep(2)
if __name__ == "__main__":
    robot_control.bus_servo_niuju_on(0xfe)#先使能
    time.sleep(2)
    for n in range(10):
        x=float(input())
        y=float(input())
        robot_pick(x,y)
    robot_control.bus_servo_all(arr1, arr2, arr3, arr4, clip_close_degree, 1000)
    time.sleep(2)
    robot_control.bus_servo_all(30, 74, 172, 198, 100, 1000)
    time.sleep(2)
    robot_control.bus_servo_all(200, 74, 172, 198, 100, 1000)
    time.sleep(2)
    robot_control.bus_servo_all(200, 74, 172, 198, 0, 1000)
    time.sleep(2)
    robot_control.bus_servo_all(30, 58, 170, 217, 0, 1000)
   

320
320
[[-1.63393534e-02  1.57868149e-04  5.12495264e+00]
 [ 5.26227162e-05  1.61025511e-02  1.91183590e+00]]
320
320
[[-1.63393534e-02  1.57868149e-04  5.12495264e+00]
 [ 5.26227162e-05  1.61025511e-02  1.91183590e+00]]
240
100
[[-1.63393534e-02  1.57868149e-04  5.12495264e+00]
 [ 5.26227162e-05  1.61025511e-02  1.91183590e+00]]
